apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Runic-Studios/Realm-deployment.git
    path: env/realm
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: realm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
