apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: realm-fleet
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - name: realm-paper
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/realm/plugins/velagones/application.conf
                  subPath: plugins-velagones-application.conf
          volumes:
            - name: config-volume
              projected:
                sources:
                  - configMap:
                      name: paper-config
