apiVersion: batch/v1
kind: Job
metadata:
  name: trove-scylladb-init
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: schema-init
          image: nuvo/docker-cqlsh:latest
          env:
            - name: CQLSH_HOST
              value: trove-scylladb
            - name: CQLSH_PORT
              value: "9042"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for ScyllaDB to be ready...";
              until cqlsh -e 'describe cluster'; do sleep 2; done;
              echo "Applying schema...";
              cqlsh -f /init/schema.cql;
              echo "Done. Stopping...";
          volumeMounts:
            - name: cql-schema
              mountPath: /init
      volumes:
        - name: cql-schema
          configMap:
            name: trove-scylladb-init-cql
