apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-sdk

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agones-sdk
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: ["agones.dev"]
    resources: ["gameservers"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-sdk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agones-sdk
subjects:
  - kind: ServiceAccount
    name: agones-sdk
