apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realm-paper-base-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
  volumeName: realm-paper-base-pv-{{ .Values.namespace }}

