apiVersion: v1
kind: PersistentVolume
metadata:
  name: world-pv-{{ .Values.namespace }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/world
    type: DirectoryOrCreate
