---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: velocity-forwarding-secret
spec:
  encryptedData:
    forwarding.secret: AgBQViMCDE+zrg8zwuafitfAeF5Zq/Z1vTGjLHF7A9gDS39lJYgaAntkvp7NYBfKDVxtO0PZsi+92o2V9BDh2GGi6uepd8kF/ms5dAZVUinkIBIqH90h6+6tyBz2oSA6sKGPLdgH1aAacidjbxVj0nT/IfnImxorGQU6KFRaW7PX6d6ZcVq+rqvXJ8rhbKL5oYzJ4ZupnzXSHWFha0UcQkcb70cHugvEITg6OTuuIm9oUJeeotnrVgbSvmoX+FYjMJc78AJNQDOcmRCNxQDfvAUl7QlZZgcBFsUC9oxKKa3Q3xlSA93T+NG2F0xzYF9GObjttqsf5pkCxy88Ae7FXCEZ8yE/Z4RvUtkb97OBmX77bCt3SOUBjBurMz/jwRNxqf8AwcfAvivS/wQuzsmJ1UQNLTEmvHvshmkPwJS0yMx+zr2acNr+0wpKqGPnwiGcJl+yzWTxVZQgR1imye4qkEtfRs/jTKDmmADFdJn3+MzNysCKaTFg57jyWhuXZ4FRpd440P2EPKOH6HBwWxaZfsKsb15KY0kmzqLh+7I8j62yHLAerpgqsrO/dc56ZIPpr50nAivbTqD1VGAsm7yVnH5BgM14uQT5+9tzK5HFbDSSReEr9J752JYVsmClH1C0y2NB3xHwCla+wcmVryPTwE3MTmPm6nqiDnX44iu/Yx2MVx10p7hFDpMJVasWR1wgaGsM3T9PGAkCtWBsDJmH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: velocity-forwarding-secret
