---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velocity-forwarding-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    forwarding.secret: AgAI7mXVg5FnPL2PDr2sCYY4t8TYFdPlFiSCEHELS+Pr7aIh7u5GaRMxvxqD02Jv+2UEapgqaXhcvA7SJNhAV+d8peaIslKTYkx0Gw5+0UrN6CvkyspUMuTQYaI5zpDRC8K7R/ngnBUYmhf36gu4WlORQQmgYMB+qI4olxiKF0fxWo9hHzJE9FkmENzbMawxLxZgmaW6VyQTJisdf94GwR4YsbkBDDuZSAspomKKW7wtirhYkWy74p61riZGUAVdo91SIvbHXjlKMshnFR+VK6gFauJza8vksmURps7UjFcQijnqjALVKw3FQ1Ac26BxiAJ3SUwn2CeSFeRkgWlVsYOgmYPrvX17ITCMbSVR4lQXRqftRWlRS9rp+n58xj1EkD5YbfYOUD9S+rXzjPgsBVSLQgxkVv5wxNKD1dvHl7Iy2LLYbSeAteGLDgCkgYLt/MDUFp41IXExq1iMWysGAD/9uKhNhElpPGpAW2/PFK0w/qIyD/q8JCjRZ1fkaDPt0Ilgicvimh2Hrl0pkMlehyKbWKC6HYpLSharkd/LBs+JBLmdK9of/at42APQkhLD9UweyGkB7faX4aS7kI5lvvJCiQRPUIzJsZfeJXfTy85aj8+w4i0Tq58mHvWkjoxM68KwHhPJCKBnDHXy3/RiMSN1MMgVslXeAK8Ic2O+/c1qdnYCO8WXQGJJFtWonEX7m1y9S0RcuLTHnU3Mcvws
  template:
    metadata:
      creationTimestamp: null
      name: velocity-forwarding-secret
      namespace: {{ .Values.namespace }}
