---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: velocity-forwarding-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    forwarding.secret: AgBcuIcDvdOOcV7BpIwabSQ/BikTtqDzB6FaE5X7iXPC1Z0+Z2GLZVREGJ+W6HiO9cn7GMgnTzBrRuPGF9wkwDbdpCVeAmMr+dF3WNlwKIAcD1vA53nAz11MBgPAwPv9+9wjfPo2VC11cmpuRmY9frBCnBEb0GvpYl0AWJ90DdQeHWV/WGok2ijhbO4aler5I4F1NVz15pIt/UxPnEMtpTljk6zLu6EwxvkAdNQJwmRhvO1CJKIfYqRwYs0lw2LqPktj8qVS8sbaF5NSw6n9DI6ehdlQeiscgDAXHLAYjBp7CuFpnmyX1kWZoMamkbdSiEt7l7Uo/FSpUQ+Xu2Md5fTv1mfQbsuxy6VIo68h2o17WUmnqecO42CbeMFhDjv6zmmdFohRhyDGPrD9ZtdXh0lmwrW76hV/i/baUUevRFnTaqd1B8jcK13nTrVPMIsTFq32Gw05FAtiOSJDnfRUBvcr1GwSCo8Kg6msP/w1gzrtHG6PY5oPdt1EUu9QQiytI2xDxZYi3iXbd8B8cUEIU/j0Ud81u4Nk1Abw47IJxzsFRLPODufjS+Y/H+7cklXhAsXotrVBwFrIW6GXXJqhuQMV1i/mv5KayPPjxFa/Cx8FF8d8yivKOnMnNa266vnN/J2Nl66F36co9K2QGEiT8IPbTsg+AZ7vXYNdCID5entHuqhtDmRXBlqacaxcy6mXaqPMON4OvI/PvnSZUbFq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: velocity-forwarding-secret
      namespace: {{ .Values.namespace }}
