apiVersion: v1
kind: PersistentVolume
metadata:
  name: realm-velocity-base-pv-{{ .Values.namespace }}
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/realm-velocity-base
    type: DirectoryOrCreate
