apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: realm-fleet
spec:
  replicas: 1
  template:
    spec:
      ports:
        - name: minecraft
          containerPort: 25565
      template:
        spec:
          containers:
            - name: papermc-gameserver
              image: marctv/minecraft-papermc-server:latest
              command: ["/bin/sh"]
              args: ["-c", "/docker-entrypoint.sh || true; tail -f /dev/null"]
              env:
                - name: MEMORYSIZE
                  value: 4G
                - name: PAPERMC_FLAGS
                  value: ""
              resources:
                requests:
                  memory: 1500Mi
                  cpu: 500m
                limits:
                  memory: 4000Mi
                  cpu: 2000m
