apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: realm-fleet
spec:
  replicas: 1
  template:
    spec:
      ports:
        - name: minecraft
          containerPort: 25565
      template:
        spec:
          containers:
            - name: papermc-gameserver
              image: itzg/minecraft-server:latest
              resources:
                requests:
                  memory: 1500Mi
                  cpu: 500m
                limits:
                  memory: 4000Mi
                  cpu: 2000m
