apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velocity-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velocity-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: velocity-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
