apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: realm-fleet
spec:
  replicas: 1
  template:
    spec:
      health:
        disabled: true
      ports:
        - name: minecraft
          containerPort: 25565
      template:
        spec:
          containers:
            - name: papermc-gameserver
              image: itzg/minecraft-server:latest
              env:
                - name: EULA
                  value: "TRUE"
              resources:
                requests:
                  memory: 1500Mi
                  cpu: 500m
                limits:
                  memory: 4000Mi
                  cpu: 2000m
