apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: realm-fleet
spec:
  replicas: 1
  template:
    spec:
      health:
        disabled: true
      ports:
        - name: minecraft
          containerPort: 25565
      template:
        spec:
          containers:
            - name: realm-paper
              image: registry.runicrealms.com/build/realm-paper:latest
              resources:
                requests:
                  memory: 1500Mi
                  cpu: 500m
                limits:
                  memory: 2500Mi
                  cpu: 1500m
